services:
  - type: web
    name: ca-delivery-vans-analytics
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && python3 -m pip install --user -r requirements.txt && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUSERBASE
        value: /opt/render/project/.python_packages
